blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path('',render_posts, name='posts'),
    path("<int:post_id>", post_detail,
         name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from blog import urls
from portafolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,
                       document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
class Post(models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

# Create your models here.

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField 

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image= ImageField(upload_to='portafolio/images')
    url = URLField(blank=True)
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
def render_posts(request):
    articulos = Post.objects.all()
    return render(request, 'posts.html' ,{'posts':articulos})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html', {"post": post})

portafolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):
    projects=Project.objects.all()
    return render(request, 'home.html'
                  ,{'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<h1>POST DE LA APLICACIÓN</h1>
<h2>{{post.title}}</h2>
<h3>{{post.date}}</h3>
<p>{{post.description|safe}}</p>
<img src="{{post.image.url}}" alt="{{post.title}}" width="300" height="250">
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}

<h1>Post hechos de "blog"</h1>

{% for post in posts %}
     <h2>{{post.title}}</h2>
     <p>{{post.description|striptags|truncatechars:100}}</p>
     <p>{{post.date|date:'M d Y'|upper}}</p>
     <img src="{{post.image.url}}" alt="{{post.title}}" width="300" height="550">

     <a href="{% url 'blog:post_detail' post.id %}">Detalle</a>
{% endfor %}
{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<header class="row bg-black">
    <div class="col-md-4">     
        <img src="{% static 'portafolio/minecraft.jpg' %}" alt="" width="250" height="300">
    </div>
    <div class="col-md-8 my auto">
        <h1>I am <strong>Vanessa Gomez</strong></h1>
        <h3>Pagina WEB</h3>
        <p>Bienvenidos a la primer pagina web que programé,
            aunque me tardé como 3 días el proceso fue muy divertido"</p>
<a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'curriculum.pdf' %}" target="_blank">
    Download CV</a>
    </div>
</header>
<div class="row my-4 text-center">
     <h1>Mis proyectos</h1>
     <p>Mis proyectos de base de datos</p>
     {% for project in projects %}
     <div class="col-md-4 p-4">
         <div class="card bg-black card-project">
              <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
             <div class="card-body">
                  <h2>{{project.title}}</h2>
                  <p>{{project.description}}</p>

                  <br>
                  {% if project.url %}
                       <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
                  {%endif %}
        </div>
    </div>
    </div>
{% endfor %}
{% endblock %}  
</div>

portafolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
    crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>
    

portafolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container-fluid">
      <a class="navbar-brand fw-bold fst-italic" href="/">Vanessa Gomez</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
       aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'curriculum.pdf' %}" target="_blank">
                Download CV</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>